server:
  port: 9988
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          # uri: https://github.com/HYUANT/microservicecloud-config.git
          uri: https://gitlab.com/kenluck/ccd-config.git
          username: kenluck
          password: 903kreBR

